site_name: CYBERDECK ACADEMY
site_url: https://adnanafo.github.io/cyberdeck-school/

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  font:
    text: VT323
    code: Roboto Mono

extra_css:
  - stylesheets/terminal.css

nav:
  - Home: index.md
  - Phase 1 Foundations: 
    - Overview: phase1-foundations/index.md
    - Lesson 1: phase1-foundations/lesson1.md